name = "sportmanager-api"
main = "./src/index.js"
compatibility_date = "2026-07-19"

env = "production"

[vars]
# These values should be set in Cloudflare dashboard or via Wrangler environment variables.
DATABASE = "sportmanager_db"
EMAIL_API_KEY = ""
EMAIL_API_URL = ""

[[d1_databases]]
binding = "D1"
database_name = "sportmanager_db"

[triggers]
crons = ["0 */6 * * *"]
